aggregation: slide
cohorts:
- TCGA
ext_cohorts: []
folds: 1
label_dict:
  Adipose-Fat: 0
  Debris-Necrosis: 1
  Tumor Infiltrating Lymphocytes: 2
  Plasma Cells: 3
  Lymphoid Aggregate: 4
  Lymphocytes: 5
  Muscle: 6
  Mucus-Mucin: 7
  Normal Mucosa: 8
  Adenoma: 9
  Tumor Associated Stroma: 10
  Carcinoma: 11
  Poorly Differentiated: 12
  Signet Ring: 13
  Background: 14
metric: bacc
num_classes: 15
num_samples: 11186
prompts:
  Adipose-Fat: 'adipose, adipose tissue, adipocytes, fat, fat cells'
  Debris-Necrosis: 'debris, necrosis, dead cells'
  Tumor Infiltrating Lymphocytes: 'tumor infiltrating lymphocytes, TILs, intraepithelial lymphocytes'
  Plasma Cells: 'plasma cells'
  Lymphoid Aggregate: 'lymphoid aggregate, lymphoid follicles'
  Lymphocytes: 'inflammatory, lymphocytes, immune cells, infiltrating lymphocytes'
  Muscle: 'smooth muscle, skeletal muscle, muscularis propria'
  Mucus-Mucin: 'mucus, mucin, mucus pool, mucin pool'
  Normal Mucosa: 'normal mucosa, uninvolved mucosa, benign'
  Adenoma: 'adenoma'
  Tumor Associated Stroma: 'tumor associated stroma'
  Carcinoma: 'adenocarcinoma, malignant tumor, carcinoma'
  Poorly Differentiated: 'poorly differentiated'
  Signet Ring: 'signet ring, medullary tumor'
  Background: 'background, empty'
target: OncoTreeCode
task: multiclass